project_id = "studio-ritua"

[auth]
site_url = "https://espi0-bat.github.io/studio-ritua/"
additional_redirect_urls = ["https://espi0-bat.github.io/studio-ritua/", "http://localhost:5173/", "http://127.0.0.1:5173/", "https://espi0-bat.github.io/studio-ritua/?admin=1", "http://localhost:5173/?admin=1", "http://127.0.0.1:5173/?admin=1"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = true
otp_length = 8
otp_expiry = 600
max_frequency = "1m"


[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
