import { useEffect, useId, useRef } from 'react'

// Three finite copies provide room to wrap in either direction without growing the DOM.
export default function ProductCarousel({ items, renderItem, reducedMotion, label = 'Produtos da Rituá' }) {
  const id = useId()
  const loop = items.length > 1
  const viewport = useRef(null)
  const cycle = useRef(0)
  const drag = useRef(null)
  const touching = useRef(false)
  const suppressClick = useRef(false)

  useEffect(() => {
    const element = viewport.current
    // Trackpads send both axes. A small deltaX must not trap a downward gesture.
    const onWheel = event => {
      if (event.ctrlKey || event.deltaX === 0 || Math.abs(event.deltaY) <= Math.abs(event.deltaX)) return
      const unit = event.deltaMode === 1 ? 16 : event.deltaMode === 2 ? window.innerHeight : 1
      if (event.cancelable) {
        event.preventDefault()
        window.scrollBy({ top: event.deltaY * unit, behavior: 'instant' })
      }
    }
    element.addEventListener('wheel', onWheel, { passive: false })
    return () => element.removeEventListener('wheel', onWheel)
  }, [])

  useEffect(() => {
    const element = viewport.current
    if (!loop) { element.scrollLeft = 0; cycle.current = 0; return }
    let timer
    let previousCycle = 0
    const measure = () => {
      const cards = element.querySelectorAll('.gallery__item')
      const nextCycle = cards[items.length].offsetLeft - cards[0].offsetLeft
      if (!nextCycle || Math.abs(nextCycle - previousCycle) < 1) return
      const progress = previousCycle ? ((element.scrollLeft % previousCycle) / previousCycle) : 0
      cycle.current = nextCycle
      previousCycle = nextCycle
      element.scrollLeft = nextCycle * (1 + progress)
    }
    const wrap = () => {
      if (drag.current || touching.current || !cycle.current) return
      const size = cycle.current
      if (element.scrollLeft < size * 0.5 || element.scrollLeft > size * 2.5) {
        const active = document.activeElement
        const focusedCard = active?.closest('[data-carousel-index]')
        const index = focusedCard?.dataset.carouselIndex
        element.scrollBy({ left: element.scrollLeft < size ? size : -size, behavior: 'instant' })
        if (index !== undefined && element.contains(active)) {
          element.querySelector(`[data-carousel-copy="1"][data-carousel-index="${index}"] button`)?.focus({ preventScroll: true })
        }
      }
    }
    const onScroll = () => {
      clearTimeout(timer)
      timer = setTimeout(wrap, 160)
    }
    measure()
    const resize = new ResizeObserver(measure)
    resize.observe(element)
    element.addEventListener('scroll', onScroll, { passive: true })
    element.addEventListener('scrollend', wrap)
    return () => {
      clearTimeout(timer)
      resize.disconnect()
      element.removeEventListener('scroll', onScroll)
      element.removeEventListener('scrollend', wrap)
    }
  }, [items.length, loop])

  const move = (direction) => {
    if (!loop) return
    const element = viewport.current
    element.scrollBy({ left: direction * cycle.current / items.length, behavior: reducedMotion ? 'instant' : 'smooth' })
  }

  const endDrag = () => {
    touching.current = false
    if (!drag.current || !loop) return
    const element = viewport.current
    const moved = suppressClick.current
    drag.current = null
    element.classList.remove('gallery__carousel--dragging')
    const step = cycle.current / items.length
    if (moved && step) element.scrollTo({ left: Math.round(element.scrollLeft / step) * step, behavior: reducedMotion ? 'instant' : 'smooth' })
    // A click generated by this pointer release must not open a product after dragging.
    setTimeout(() => { suppressClick.current = false }, 0)
  }

  return (
    <div className="gallery__carousel-region" role="region" aria-roledescription="carrossel" aria-label={label}>
      <div className={`gallery__carousel${items.length === 2 ? ' gallery__carousel--pair' : ''}${loop ? ' gallery__carousel--loop' : ''}`} id={id} ref={viewport}
        onDragStart={event => event.preventDefault()}
        onPointerDown={event => {
          suppressClick.current = false
          touching.current = event.pointerType === 'touch'
          if (!loop || event.pointerType !== 'mouse' || event.button !== 0) return
          drag.current = { start: event.clientX, startY: event.clientY, scroll: viewport.current.scrollLeft }
        }}
        onPointerMove={event => {
          if (!drag.current) return
          const distance = event.clientX - drag.current.start
          if (!suppressClick.current && Math.abs(event.clientY - drag.current.startY) > Math.abs(distance)) { drag.current = null; return }
          if (Math.abs(distance) > 6) {
            suppressClick.current = true
            viewport.current.classList.add('gallery__carousel--dragging')
            if (!viewport.current.hasPointerCapture(event.pointerId)) viewport.current.setPointerCapture(event.pointerId)
          }
          if (suppressClick.current) viewport.current.scrollLeft = drag.current.scroll - distance
        }}
        onPointerUp={endDrag} onPointerCancel={endDrag}
        onPointerLeave={() => { if (!suppressClick.current) drag.current = null }}
        onClickCapture={event => {
          if (suppressClick.current) { event.preventDefault(); event.stopPropagation() }
        }}
        onKeyDown={event => {
          if (!loop) return
          if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
            event.preventDefault()
            const card = event.target.closest('[data-carousel-index]')
            if (card) {
              const index = (Number(card.dataset.carouselIndex) + (event.key === 'ArrowRight' ? 1 : -1) + items.length) % items.length
              const next = viewport.current.querySelector(`[data-carousel-copy="1"][data-carousel-index="${index}"]`)
              next.querySelector('button').focus({ preventScroll: true })
              move(event.key === 'ArrowRight' ? 1 : -1)
            } else move(event.key === 'ArrowRight' ? 1 : -1)
          }
        }}>
        <div className="gallery__track">
          {(loop ? [0, 1, 2] : [1]).flatMap(copy => items.map((item, index) => (
            <figure className="gallery__item" key={`${copy}-${item.id}`}
              data-carousel-copy={copy} data-carousel-index={index}
              aria-hidden={copy !== 1 ? true : undefined}>
              {renderItem(item, index, copy !== 1)}
            </figure>
          )))}
        </div>
      </div>
      {loop && <div className="gallery__carousel-controls">
        <p>Deslize para ver as peças</p>
        <div>
          <button type="button" aria-label="Produto anterior" aria-controls={id} onClick={() => move(-1)}>←</button>
          <button type="button" aria-label="Próximo produto" aria-controls={id} onClick={() => move(1)}>→</button>
        </div>
      </div>}
    </div>
  )
}
