import { useEffect, useRef } from 'react'

// Three finite copies provide room to wrap in either direction without growing the DOM.
export default function ProductCarousel({ items, renderItem, reducedMotion }) {
  const viewport = useRef(null)
  const cycle = useRef(0)
  const drag = useRef(null)
  const suppressClick = useRef(false)

  useEffect(() => {
    const element = viewport.current
    let timer
    let previousCycle = 0
    const measure = () => {
      const cards = element.querySelectorAll('.gallery__item')
      const nextCycle = cards[items.length].offsetLeft - cards[0].offsetLeft
      const progress = previousCycle ? ((element.scrollLeft % previousCycle) / previousCycle) : 0
      cycle.current = nextCycle
      previousCycle = nextCycle
      element.scrollLeft = nextCycle * (1 + progress)
    }
    const wrap = () => {
      if (drag.current || !cycle.current) return
      const size = cycle.current
      if (element.scrollLeft < size || element.scrollLeft >= size * 2) {
        const active = document.activeElement
        const focusedCard = active?.closest('[data-carousel-index]')
        const index = focusedCard?.dataset.carouselIndex
        element.scrollLeft = size + ((element.scrollLeft % size) + size) % size
        if (index !== undefined && element.contains(active)) {
          element.querySelector(`[data-carousel-copy="1"][data-carousel-index="${index}"] button`)?.focus({ preventScroll: true })
        }
      }
    }
    const onScroll = () => {
      clearTimeout(timer)
      timer = setTimeout(wrap, 160)
    }
    measure()
    const resize = new ResizeObserver(measure)
    resize.observe(element)
    element.addEventListener('scroll', onScroll, { passive: true })
    element.addEventListener('scrollend', wrap)
    return () => {
      clearTimeout(timer)
      resize.disconnect()
      element.removeEventListener('scroll', onScroll)
      element.removeEventListener('scrollend', wrap)
    }
  }, [items.length])

  const move = (direction) => {
    const element = viewport.current
    element.scrollBy({ left: direction * cycle.current / items.length, behavior: reducedMotion ? 'instant' : 'smooth' })
  }

  const endDrag = () => {
    if (!drag.current) return
    const element = viewport.current
    drag.current = null
    element.classList.remove('gallery__carousel--dragging')
    const step = cycle.current / items.length
    element.scrollTo({ left: Math.round(element.scrollLeft / step) * step, behavior: reducedMotion ? 'instant' : 'smooth' })
    // A click generated by this pointer release must not open a product after dragging.
    setTimeout(() => { suppressClick.current = false }, 0)
  }

  return (
    <div className="gallery__carousel-region" role="region" aria-roledescription="carrossel" aria-label="Produtos da Rituá">
      <div className="gallery__carousel" id="ritua-products" ref={viewport}
        onDragStart={event => event.preventDefault()}
        onPointerDown={event => {
          suppressClick.current = false
          if (event.pointerType !== 'mouse' || event.button !== 0) return
          drag.current = { start: event.clientX, scroll: viewport.current.scrollLeft }
        }}
        onPointerMove={event => {
          if (!drag.current) return
          const distance = event.clientX - drag.current.start
          if (Math.abs(distance) > 6) {
            suppressClick.current = true
            viewport.current.classList.add('gallery__carousel--dragging')
            if (!viewport.current.hasPointerCapture(event.pointerId)) viewport.current.setPointerCapture(event.pointerId)
          }
          if (suppressClick.current) viewport.current.scrollLeft = drag.current.scroll - distance
        }}
        onPointerUp={endDrag} onPointerCancel={endDrag}
        onPointerLeave={() => { if (!suppressClick.current) drag.current = null }}
        onClickCapture={event => {
          if (suppressClick.current) { event.preventDefault(); event.stopPropagation() }
        }}
        onKeyDown={event => {
          if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') {
            event.preventDefault()
            const card = event.target.closest('[data-carousel-index]')
            if (card) {
              const index = (Number(card.dataset.carouselIndex) + (event.key === 'ArrowRight' ? 1 : -1) + items.length) % items.length
              const next = viewport.current.querySelector(`[data-carousel-copy="1"][data-carousel-index="${index}"]`)
              next.querySelector('button').focus({ preventScroll: true })
              move(event.key === 'ArrowRight' ? 1 : -1)
            } else move(event.key === 'ArrowRight' ? 1 : -1)
          }
        }}>
        <div className="gallery__track">
          {[0, 1, 2].flatMap(copy => items.map((item, index) => (
            <figure className="gallery__item" key={`${copy}-${item.id}`}
              data-carousel-copy={copy} data-carousel-index={index}
              aria-hidden={copy !== 1 ? true : undefined}>
              {renderItem(item, index, copy !== 1)}
            </figure>
          )))}
        </div>
      </div>
      <div className="gallery__carousel-controls">
        <p>Deslize para ver as peças</p>
        <div>
          <button type="button" aria-label="Produto anterior" aria-controls="ritua-products" onClick={() => move(-1)}>←</button>
          <button type="button" aria-label="Próximo produto" aria-controls="ritua-products" onClick={() => move(1)}>→</button>
        </div>
      </div>
    </div>
  )
}
